### PR TITLE
chore(deps): run yarn-deduplicate

### PR DESCRIPTION
**Pull request by abdonrd**
Run `yarn-deduplicate`

### CODE REVIEW

**Comment by abdonrd** [comment]
Right now, all checks are green!

**Comment by abdonrd** [comment]
Right now, until [81d982c](https://github.com/carbon-design-system/carbon-web-components/pull/813/commits/07a4bc96d86862287bd0186debd52ee4a0171ebe), all checks are green!

**Comment by abdonrd** [comment]
Right now, until https://github.com/carbon-design-system/carbon-web-components/pull/813/commits/7ce330b2a640eb81c57702a4b3fead4f8d654e7b, all checks are green!

**Comment by abdonrd** [comment]
Right now, until https://github.com/carbon-design-system/carbon-web-components/pull/813/commits/773daf6481437c74baf19d91ce03380f8d2c29e3, all checks are green!

**Review by jeffchew — APPROVED** [review]
Thank you @abdonrd !

**Pull request merged**
