### PR TITLE
chore(dependencies): update sass & sass-loader

### PR DESCRIPTION
**Pull request by abdonrd**
Update sass & sass-loader

### CODE REVIEW

**Comment by jeffchew** [comment]
Seeing the same diffs from the other dependency upgrade PR, wonder if it's a sass thing?

image

**Comment by abdonrd** [comment]
Yeah! Ghost found!

**Comment by abdonrd** [comment]
Seems like the issue is with `sass`.

**Comment by abdonrd** [comment]
Breaks from sass v1.40 to v1.41:

- https://github.com/carbon-design-system/carbon-web-components/pull/741/commits/372dfca7362c1d403a54cbea8041b3273baf27d7
- https://percy.io/538fc19a/Carbon-Web-Components/builds/13730936/changed/777211317?browser=chrome&browser_ids=20&subcategories=unreviewed%2Cchanges_requested&viewLayout=overlay&viewMode=new&width=1280&widths=320%2C1280

**Comment by abdonrd** [comment]
Here the example in another PR:
https://github.com/carbon-design-system/carbon-web-components/pull/756

**Review by jeffchew — APPROVED** [review]
LGTM!

**Pull request merged**
