### PR TITLE
chore: update Node to the LTS version (v16)

### LINKED ISSUE #733: Update Node to LTS version
### The problem

We are not using the Node LTS version

### The solution

Update Node to LTS version

### Application/website

-

### Business priority

Low Priority = release date is not dependent on fix or not upcoming

### What time frame would this ideally be needed by (if applicable)

_No response_

### Examples

_No response_

### Code of Conduct

- [X] I agree to follow this project's [Code of Conduct](https://github.com/carbon-design-system/carbon-web-components/blob/master/.github/CODE_OF_CONDUCT.md)
- [X] I checked the [current issues](https://github.com/carbon-design-system/carbon-web-components/issues) for duplicate issues

### PR DESCRIPTION
**Pull request by abdonrd**
### Changelog

**Changed**

- Update Node to the LTS version (v16)

Fix #733

### CODE REVIEW

**Comment by abdonrd** [comment]
Seems like v14 works without any issue, but the v16 does not.

**Comment by jeffchew** [comment]
> Seems like v14 works without any issue, but the v16 does not.

Yes, we might nee to create an issue to investigate what is preventing the Node 16 upgrade.

**Comment by abdonrd** [comment]
@jeffchew now with the updated deps, it works!

**Review by jeffchew — APPROVED** [review]
LGTM! We will need to update the required checks before letting this one in. I'll do that when the PR is ready for merging.

**Comment by abdonrd** [comment]
@jeffchew ready now!

**Pull request merged**
