### PR TITLE
fix(select): add custom selected event for select component

### PR DESCRIPTION
**Pull request by annawen1**
### Related Ticket(s)

<bx-select> '@input' event does not work ('oninput' works, but not in Firefox). #665

### Description

Add `bx-select-selected` custom event that's dispatched when item is selected from `select` component

### Changelog

**New**

- `bx-select-selected` custom event added to `select` component

### CODE REVIEW

**Review by jeffchew — APPROVED** [review]
LGTM!

**Comment by rkgriff** [comment]
@jeffchew  hi Jeff, can you let me know how we can get this change in new bundle?  The link above for deploy preview created for `Carbon Web Components` brings up version 1.14.1.  Would we just install this version by doing `npm install --save carbon-web-components@1.14.1`?  Or do we get this update some other way?  Thanks.

**Comment by jeffchew** [comment]
@rkgriff you can run the following in your project:

```
npm update carbon-web-components@latest
```

**Comment by rkgriff** [comment]
@jeffchew Thanks Jeff.  If I run `npm update carbon-web-components@latest` in my project it says everything is up to date.  But, I still see this version listed in my package.json file - "carbon-web-components": "^1.13.3".  Doing something wrong?  Thanks.

**Comment by annawen1** [comment]
@rkgriff Since you're using the `^` prepended to the version, your project should already be using 1.14.1

`^version` will update you to all future minor/patch versions, without incrementing the major version (ie.  ^1.13.3 will use releases from 1.13.3 to <2.0.0)

You can also go into the package.json file and manually change the version:
```
"carbon-web-components": "1.15.1"
```
and then run `npm install`

**Comment by rkgriff** [comment]
@annawen1 Thanks.

**Pull request merged**
