### PR TITLE
chore(deps): update dependencies

### PR DESCRIPTION
**Pull request by abdonrd**
Update dependencies

### CODE REVIEW

**Comment by kennylam** [comment]
Thanks for this @abdonrd! Looks like the Angular stories aren't loading correctly.

image

**Review by kennylam — COMMENTED** [review]
Thanks for this @abdonrd! Looks like the Angular stories aren't loading correctly.

image

**Comment by abdonrd** [comment]
@kennylam still pending for the latest update:

Screenshot 2021-11-17 at 14 43 13

**Comment by abdonrd** [comment]
All checks working now!

**Comment by kennylam** [comment]
> All checks working now!

@abdonrd Sorry if I wasn't clear. It's not the deploy preview build I was referring to. None of the stories are loading properly. They all throw the `properties of undefined` error. Perhaps this started with a previous deps update?

**Comment by abdonrd** [comment]
> > All checks working now!
> 
> @abdonrd Sorry if I wasn't clear. It's not the deploy preview build I was referring to. None of the Angular stories are loading properly. They all throw the `properties of undefined` error. Perhaps this started with a previous deps update?

Oh, got it!
Sorry, we have not realized that! I'll investigate.

**Comment by abdonrd** [comment]
@kennylam wow, it's an "old" issue... It happens even here:
- https://github.com/carbon-design-system/carbon-web-components/pull/794

**Comment by abdonrd** [comment]
Maybe with this:

- https://github.com/carbon-design-system/carbon-web-components/pull/767

**Comment by abdonrd** [comment]
@kennylam maybe we can merge this and send another PR to downgraded the storybook deps.

**Comment by kennylam** [comment]
> maybe we can merge this and send another PR to downgraded the storybook deps.

Sounds good!

**Review by kennylam — APPROVED** [review]
LGTM thanks @abdonrd!

**Pull request merged**
